# .goreleaser.yml
# Build customization
builds:
  - binary: prjbrain 
    goos:
      - linux
    goarch:
      - amd64
    hooks:
      pre: packr
      post: packr clean
archives:
  -
    format: tar.gz
    files:
      - config.yml

