# .goreleaser.yml
# Build customization
builds:
  - binary: prjbrain 
    goos:
      - windows
      - linux
    goarch:
      - amd64
    hooks:
      pre: packr
      post: packr clean
archive:
  format: tar.gz
  files:
    - config.yml

